trigger:
  branches:
    include:
      - main  # or your desired branch

pool:
  vmImage: 'ubuntu-latest'

variables:
  NODE_ENV: 'test'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'  # your preferred Node.js version
  displayName: 'Install Node.js'

- script: |
    npm ci
    npx playwright install
  displayName: 'Install dependencies and Playwright browsers'

- script: |
    npx playwright test --reporter=html
  displayName: 'Run Playwright tests'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: 'playwright-report'
    artifact: 'playwright-report'
  condition: always()
  displayName: 'Publish Playwright HTML Report'
