version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies..."
      - npm ci
      - echo "Installing Playwright..."
      - npx playwright install --with-deps
      - echo "Setting ENV=local..."
      - export ENV=local

  build:
    commands:
      - echo "Running all Playwright tests..."
      - npx playwright test




